"""
Konstantendeklarationen für die MCP Integration Suite.

Status: PARTIAL
Version: 0.1.0
Checkpoint: CHECKPOINT-INITIAL
Letztes Update: 2023-04-24
"""

__version__ = "0.1.0"
__status__ = "development"
__last_updated__ = "2023-04-24"

# Domain-Name für die Integration
DOMAIN = "mcp_integration"

# Integration-Typen
INTEGRATION_MS365 = "ms365"
INTEGRATION_BOOKSTACK = "bookstack"
INTEGRATION_LOKI = "loki"

# Liste aller unterstützten Integrationen
SUPPORTED_INTEGRATIONS = [INTEGRATION_MS365, INTEGRATION_BOOKSTACK, INTEGRATION_LOKI]

# Konfigurationsschlüssel
CONF_INTEGRATION_TYPE = "integration_type"
CONF_NAME = "name"
CONF_HOST = "host"
CONF_PORT = "port"
CONF_API_KEY = "api_key"
CONF_API_SECRET = "api_secret"
CONF_CLIENT_ID = "client_id"
CONF_CLIENT_SECRET = "client_secret"
CONF_TOKEN = "token"

# Standard-Ports
DEFAULT_PORT_MS365 = 3001
DEFAULT_PORT_BOOKSTACK = 3000
DEFAULT_PORT_LOKI = 3002

# Entity-Kategorien
ENTITY_CATEGORY_DIAGNOSTICS = "diagnostic"
ENTITY_CATEGORY_CONFIG = "config"

# Status-Konstanten
STATUS_ONLINE = "online"
STATUS_OFFLINE = "offline"
STATUS_ERROR = "error"

# Log-Levels
LOG_LEVEL_DEBUG = "debug"
LOG_LEVEL_INFO = "info"
LOG_LEVEL_WARNING = "warning"
LOG_LEVEL_ERROR = "error"

# Checkpoint-Definitionen
CHECKPOINT_INITIAL = "CHECKPOINT-INITIAL"
CHECKPOINT_P1_BASE = "CHECKPOINT-P1-BASE"
CHECKPOINT_P1_TRANSPORT = "CHECKPOINT-P1-TRANSPORT"
CHECKPOINT_P1_TOOLS = "CHECKPOINT-P1-TOOLS"
CHECKPOINT_P1_CORE = "CHECKPOINT-P1-CORE"

CHECKPOINT_P2_OAUTH = "CHECKPOINT-P2-OAUTH"
CHECKPOINT_P2_APIKEY = "CHECKPOINT-P2-APIKEY"
CHECKPOINT_P2_SESSION = "CHECKPOINT-P2-SESSION"
CHECKPOINT_P2_AUTH = "CHECKPOINT-P2-AUTH"

CHECKPOINT_P3_MS365_BASE = "CHECKPOINT-P3-MS365-BASE"
CHECKPOINT_P3_MS365_TOOLS = "CHECKPOINT-P3-MS365-TOOLS"
CHECKPOINT_P3_MS365 = "CHECKPOINT-P3-MS365"

CHECKPOINT_P3_BOOKSTACK_BASE = "CHECKPOINT-P3-BOOKSTACK-BASE"
CHECKPOINT_P3_BOOKSTACK_TOOLS = "CHECKPOINT-P3-BOOKSTACK-TOOLS"
CHECKPOINT_P3_BOOKSTACK = "CHECKPOINT-P3-BOOKSTACK"

CHECKPOINT_P3_LOKI_BASE = "CHECKPOINT-P3-LOKI-BASE"
CHECKPOINT_P3_LOKI_TOOLS = "CHECKPOINT-P3-LOKI-TOOLS"
CHECKPOINT_P3_LOKI = "CHECKPOINT-P3-LOKI"

CHECKPOINT_P4_MANIFEST = "CHECKPOINT-P4-MANIFEST"
CHECKPOINT_P4_CONFIG = "CHECKPOINT-P4-CONFIG"
CHECKPOINT_P4_ENTITIES = "CHECKPOINT-P4-ENTITIES"
CHECKPOINT_P4_HA = "CHECKPOINT-P4-HA"

CHECKPOINT_P5_INTENTS = "CHECKPOINT-P5-INTENTS"
CHECKPOINT_P5_HANDLERS = "CHECKPOINT-P5-HANDLERS"
CHECKPOINT_P5_CONTEXT = "CHECKPOINT-P5-CONTEXT"
CHECKPOINT_P5_VOICE = "CHECKPOINT-P5-VOICE"

# Endpunkt-Definitionen für verschiedene Dienste
MS365_GRAPH_API_BASE = "https://graph.microsoft.com/v1.0"
MS365_GRAPH_API_BETA = "https://graph.microsoft.com/beta"

# OAuth2-Scopes für Microsoft 365
MS365_SCOPES = [
    "offline_access",
    "User.Read",
    "Mail.Read",
    "Mail.ReadWrite",
    "Calendars.Read",
    "Calendars.ReadWrite",
    "Files.Read",
    "Files.ReadWrite"
]

# Datei-Pfade für Checkpoints und Logs
CHECKPOINT_DIR = ".checkpoints"
LOG_DIR = "logs"